events {}

http {
    server_tokens off;

    upstream books_backend {
        server books_service:5000;
    }

    upstream users_backend {
        server users_service:5000;
    }

    upstream orders_backend {
        server orders_service:5000;
    }

    server {
        listen 80;

        location = /api/books {
            proxy_pass http://books_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /api/books;
        }

        location /api/books/ {
            proxy_pass http://books_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /api/books;
        }

        location = /api/users {
            proxy_pass http://users_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /api/users;
        }

        location /api/users/ {
            proxy_pass http://users_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /api/users;
        }

        location = /api/orders {
            proxy_pass http://orders_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /api/orders;
        }

        location /api/orders/ {
            proxy_pass http://orders_backend/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Prefix /api/orders;
        }
    }
}
